### ISSUE TITLE
Error 1102 | Worker exceeded resource limits

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/web#115]
![image](https://github.com/pi-base/web/assets/1559632/94555bef-9b71-4af9-b5a8-7c9913c3b2aa)

While reviewing `pi-base/data` branches, I'm hitting this error every so often.

**Comment by StevenClontz** [comment]
Strangly, I'll hit this most often when looking at a URL like https://topology.pages.dev/spaces/S000088/properties/P000032 (for a space/property pair that doesn't exist on main), which 404s if it does work. Then I'll load https://topology.pages.dev/spaces/S000088 and click through to P32 using the site and generally don't have an issue.

**Comment by jamesdabbs** [comment]
I _think_ I fixed this at some point. Have you seen it lately?

**Comment by StevenClontz** [comment]
I have not.
