### ISSUE TITLE
Issues with trailing slashes in routes

### ISSUE THREAD

**Issue by marswill** [pi-base/web#135]
As discussed in #133 (though the issue seems to be in the main branch)

Going to the main page, https://topology.pi-base.org/
then clicking on the spaces tab, then clicking on an individual space, seems to lead to a situation where the tabs on that space (properties and references) have broken links with an extra slash - leading for example to https://topology.pi-base.org/spaces/S000005//references, which gives a 404.

On the other hand, after landing on the 404 page, if one continues to navigate through the site (including going back in the browser), the tabs seem to be repaired and everything works fine.

Also, direct linking to a space's page seems to avoid this issue, e.g., https://topology.pi-base.org/spaces/S000005/

Finally, the same issue appears to happen with individual Properties and Theorems as well.

**Comment by StevenClontz** [comment]
I have a hacky solution at #136 to just check for the extra slash and drop it.

What's not clear to me is why sometimes we're linking to `/spaces/all/` and sometimes `/spaces/all`. And why sometimes we successfully redirect `/spaces/all/` to `/spaces/all` and sometims we don't.
