### ISSUE TITLE
Incorrect browser title when navigating between properties

### ISSUE THREAD

**Issue by prabau** [pi-base/web#156]
When I am on the page for a particular property, like https://topology.pi-base.org/properties/P000011, the page correctly shows "P11: Regular" in the browser tab.  Then I click on one of the links for one of the properties that appear in the list of theorems on that page, for example Lindelöf (P18) as part of T30.  It correctly goes to https://topology.pi-base.org/properties/P000018, but the browser tab still shows "P11: Regular" instead of the expected "P18: Lindelöf".

And same kind of problem when navigating from a Theorem page to another Theorem page.  For example, from https://topology.pi-base.org/theorems/T000107 and clicking on T14.

Or navigating from spaces to spaces.  For example, from https://topology.pi-base.org/spaces/S000077 and clicking on the link for "Irrational numbers".

**Comment by StevenClontz** [comment]
pretty sure I know what's happening here - I'll try to make a quick fix

**Comment by StevenClontz** [comment]
Actually it wasn't what I thought - I thought we needed `$: title = 'foo'`, but that was already there. I got it to work by using `{#key title}<Title {title}/>{/key}` but it'd be better to not require reinstantiating that component each time the route changes. Actually, I have one more idea...

**Comment by StevenClontz** [comment]
Putting the `#key` in the title component itself did the trick.

**Comment by StevenClontz** [comment]
Always nice when the bugs are easily squashed 😅
