### ISSUE TITLE
All builds are currently failing!

### ISSUE THREAD

**Issue by prabau** [pi-base/web#167]
The builds are failing in the "Set up job" phase:

> Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v1.0.0`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

It seems some version of something needs to be updated (see link).

**Comment by StevenClontz** [comment]
Looking into this.

**Comment by StevenClontz** [comment]
Thanks for the ping @prabau... too little time for me to do actual topology this week, but I've updated all the PRs with this fix.
