### ISSUE TITLE
Add sync button to footer of every page

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/web#176]
Button is at https://topology.pi-base.org/dev but would be useful on every page so folks know when they have stale data.

**Comment by prabau** [comment]
FYI, even when I navigate to the Advanced page and click on Sync while on a specific branch, very often this does not pick up the latest version of that branch, even minutes after it should already be available.
A Sync button on every page is not going to help much unless this can also be fixed.

**Comment by StevenClontz** [comment]
I think this is a browser caching issue: one workaround is to open the JSON file directly (which is part of why I added the link to it), then right-click > Inspect, then right-click Refresh and select "Empty cache and reload".

There should be a more elegant solution, obviously.

**Comment by StevenClontz** [comment]
Closed by #182 but I'll open a new issue for the caching discussion.
