### ISSUE TITLE
Flip `topology.pi-base.org` to point to Cloudflare pages

### ISSUE THREAD

**Issue by jamesdabbs** [pi-base/web#53]
Once [all the other open items in the `prerelease` milestone](https://github.com/pi-base/web/issues?q=is%3Aissue+milestone%3Aprerelease) are `closed`.

* [x] Confirm issues [here](https://github.com/orgs/pi-base/discussions/464) are resolved
* [ ] Do a final UAT pass
  * [ ] Run Cypress tests against `topology.pages.dev`
* [ ] Follow [Cloudflare's directions](https://dash.cloudflare.com/78c505984bbdc3e69206eecb9471c4de/pages/view/topology/domains) for configuring DNS

# 🔬 Testing Notes

* [ ] Ensure [`topology.pi-base.org`](https://topology.pi-base.org) has updated
* [ ] Ensure `topology.jdabbs.com` legacy deep links (e.g. [`topology.jdabbs.com/spaces?text=plank`](https://topology.jdabbs.com/spaces?text=plank)) redirect as expected

**Comment by StevenClontz** [comment]
I will do an initial preview for the `/data` maintainer community on June 2, and have them report any issues here if they find any.

**Comment by StevenClontz** [comment]
We ended up not previewing it together live, but I've started a conversation at https://github.com/orgs/pi-base/discussions/321 for async feedback.

**Comment by jamesdabbs** [comment]
✅
