### ISSUE TITLE
Syntax for referring to a specific property in a specific space

### ISSUE THREAD

**Issue by prabau** [pi-base/web#66]
As discussed in https://github.com/pi-base/data/pull/329, we already have a syntax to refer to a specific space or a specific property, like {S76} or {P18}.  It would be handy if we could also refer to the justification for a specific property in a specific space using a syntax like {S76/P18} for example.

(This is low priority.)

**Comment by prabau** [comment]
Awesome.  Is that available in the existing web version, or is that for the next generation?

**Comment by prabau** [comment]
As for the displayed syntax, we'll have to see what reads best.  Right now, it displays as a vertical bar between the space name and the property name.  But if we use it in text, it would be good to better match the title of the linked page, and specifically the difference between when the property is true and false. (not sure how easy it would be to implement)

As an example, suppose we want to use in some text the fact that the Arens-Fort Space (S13) is normal (P13).  The following: "... blah blah because {S23|P13}." could be rendered in various ways, for example (ignoring the hyperlinks here, but imagine they are in the right spot):
- ... blah blah because Arens-Fort Space | Normal.
- ... blah blah because Arens-Fort Space is Normal.
- ... blah blah because "Arens-Fort Space is Normal".

And for a negative example: "... blah blah because {S48|P13}." could render in these ways, for example:
- ... blah blah because Prime integer topology | Normal.
- ... blah blah because Prime integer topology is not Normal.
- ... blah blah because "Prime integer topology is not Normal".

I think the second version is better than the first.  The third with enclosing double quotes seems overkill, as the hyperlinks will make clear what goes together.  Other ideas?  What do you think?

**Comment by StevenClontz** [comment]
> Awesome. Is that available in the existing web version, or is that for the next generation?

All development is for the upcoming re-release previewable at https://topology.pages.dev

**Comment by StevenClontz** [comment]
I agree that I prefer

> [Space is [not] Property](#)

over the current

> [Space | Property](#)

So I'll open an issue.
