### ISSUE TITLE
Automatic deduction of converses

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/web#72]
From today's discussion at https://github.com/orgs/pi-base/discussions/436

Right now we have a place to add Theorems that can be used to deduce the converse of a given Theorem (when the converse holds). However, is this necessary? Can't the pi-Base automatically deduce these in the same way that trying to search for the negation of that converse would result in a list of theorems?

**Comment by jamesdabbs** [comment]
Is [this](https://topology.pages.dev/theorems/T000023) the sort of auto-deduced converse you're looking for?

**Comment by StevenClontz** [comment]
looks great!

**Comment by StevenClontz** [comment]
This was closed by some commit at some point.
