### ISSUE TITLE
navigating back to `/spaces`

### ISSUE THREAD

**Issue by StevenClontz** [pi-base/web#77]
When I navigate using "back" in my browser to `/search`, the route doesn't re-render the page until I refresh the browser.

**Comment by jamesdabbs** [comment]
Reported [here](https://github.com/orgs/pi-base/discussions/464#discussioncomment-7561200). I _suspect_ it's the same root cause as [this similar report](https://github.com/orgs/pi-base/discussions/464#discussioncomment-7561621).
